### ISSUE TITLE
Managed Web Service update to Debian 9 crippled this plugin

### ISSUE THREAD

**Issue by ctr26** [gfarrell/WPRavenAuth#50]
Hi all,

This plugin was working very well until the MWS recently upgraded to debian 9. Now wp-login.php fails with a too many redirects whenever one tries to access the page. Any advice very welcome

**Comment by Burgch** [comment]
Could you capture the network traffic with web developer tools in Chrome or
Firefox and send a screenshot of the redirects please?

**Comment by ctr26** [comment]
![image](https://user-images.githubusercontent.com/15238739/60977498-7dbb7500-a327-11e9-8c70-3382e030d42c.png)

**Comment by ctr26** [comment]
http://mcr.magd.cam.ac.uk/wp-login.php

btw

**Comment by mhhadfield** [comment]
We had this *exact* issue - luckily it was resolved by replacing the
WordPress plugin files with newly downloaded ones from github files .
Didn't troubleshoot it too far past that as it worked but possible
something about the 'new' file permissions after its migration to D9. Did
that work for you?
M

**Comment by Burgch** [comment]
Thanks! I wonder if this might just be because the browser and server have
gotten out of sync with cookies etc. - might also be worth clearing cookies
for  http://mcr.magd.cam.ac.uk <http://mcr.magd.cam.ac.uk/wp-login.php> from
your browser and checking that "disable cache" button in the developer menu?

It's also worth checking that the time on the server is correct and agrees
with the Raven server.
